# Server Port
server.port=8080

# Cấu hình H2 Database (Database chạy trực tiếp trên RAM phục vụ việc test)
spring.datasource.url=jdbc:h2:mem:teadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cho phép dùng giao diện H2 Console tại localhost:8080/h2-console
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true